FROM ubuntu:22.04 as base

RUN set -eux; \
    sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirrors.aliyun.com/ubuntu|g; s|http://security.ubuntu.com/ubuntu|http://mirrors.aliyun.com/ubuntu|g' /etc/apt/sources.list; \
    sed -i 's|^deb |deb [trusted=yes] |g' /etc/apt/sources.list; \
    rm -f /etc/apt/apt.conf.d/docker-clean; \
    export JAVA_TOOL_OPTIONS="-XX:ActiveProcessorCount=1 -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Xms16m -Xmx64m"; \
    DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y libnuma-dev openssl libcurl4-openssl-dev binutils-dev libssl-dev \
        libgmp-dev libmpfr-dev libmpc-dev libisl-dev \
        make automake autoconf ninja-build cmake gperf \
        flex bison gcc-12 g++-12 \
        python3 python3-pip python3-dev openjdk-17-jdk \
        vim git openssh-client wget bzip2 && \
    unset JAVA_TOOL_OPTIONS && \
    ln -sf /usr/bin/gcc-12 /usr/local/bin/gcc && \
    ln -sf /usr/bin/g++-12 /usr/local/bin/g++ && \
    mkdir -p /usr/lib/jvm && \
    ln -sfn "$(dirname "$(dirname "$(readlink -f "$(command -v javac)")")")" /usr/lib/jvm/java-17-openjdk

ARG BUILD_DIR=/tmp/build
ARG MAVEN_VERSION=3.9.12


# Use the distro CMake to avoid bootstrap failures in this Docker environment.
RUN cmake --version

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk
ENV PATH "$JAVA_HOME/bin:$PATH"

# Install maven
ARG MAVEN_DIR=/opt/maven/apache-maven-${MAVEN_VERSION}
ARG MAVEN_URL=https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
RUN mkdir -p ${MAVEN_DIR} && \
    wget -qO- ${MAVEN_URL} | tar -zxf - -C  ${MAVEN_DIR} --strip-components=1 && \
    ln -sf ${MAVEN_DIR}/bin/mvn /usr/bin/mvn
ENV MAVEN_HOME ${MAVEN_DIR}
ENV PATH ${MAVEN_HOME}/bin:${PATH}

# Install Conan and Python dependencies without the Miniconda installer, which
# starts worker threads that are blocked in some Docker build environments.
RUN PIP_PROGRESS_BAR=off python3 -m pip install --disable-pip-version-check --upgrade pip || true && \
    PIP_PROGRESS_BAR=off python3 -m pip install --disable-pip-version-check pydot conan && \
    conan profile detect

# Install Python test dependencies required by Spark UTs (pyspark-driven tests).
RUN PIP_PROGRESS_BAR=off pip install --disable-pip-version-check \
    pyspark==3.5.5 cython pandas==2.2.3 pyarrow==20.0.0

COPY .github/workflows/util/install-spark-resources.sh /usr/local/bin/install-spark-resources.sh
RUN chmod +x /usr/local/bin/install-spark-resources.sh && \
    /usr/local/bin/install-spark-resources.sh 3.5 /opt/

RUN apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/build
